name: Execução de Testes de Regressão

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 9,11,15,18 * * 1,2,3,4,5'

jobs:
  testes-e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Projeto
        uses: actions/checkout@v2

      - name: Setup Node.js Environment
        uses: actions/setup-node@v2
        with:
          node-version: 14.x # Certifique-se de que esta versão seja adequada para o seu projeto

      - name: Install Dependencies
        run: npm install # Isso instalará todas as dependências listadas em package.json

      - name: Run Unit Tests
        run: npm run test # Ajuste isso para corresponder ao comando de teste do seu projeto

